### ISSUE TITLE
.idea should be gitignored

### ISSUE THREAD

**Issue by hmert** [academic/harvester#1]

**Comment by ismailbaskin** [comment]
Don't use user spesific file patterns in .gitignore. It would be more appropriate to use .gitignore_global .

> \# Declare the global .gitignore
> git config --global core.excludesfile ~/.gitignore_global
> 
> \# Create the .gitignore_global file
> touch .gitignore_global
> 
> \# Go into edit mode so you can add the unwanted file listing
> vim .gitignore_global

**Comment by musaceylan** [comment]
sure thnx

**Comment by hmert** [comment]
871637f473ee6a002f77224333199b19c7d24f83
