### ISSUE TITLE
PDF Parser

### ISSUE THREAD

**Issue by hmert** [academic/harvester#20]

**Comment by fakturk** [comment]
Useful sources for solving this problem

- https://speakerdeck.com/elastic/ingest-node-re-indexer-et-enrichir-des-documents-dans-elasticsearch-softshake-2016

- https://www.elastic.co/elasticon/tour/2017/seoul-ingest-and-elastic-stack

- https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html

- https://www.elastic.co/guide/en/elasticsearch/plugins/current/ingest.html
